services:
  - type: web
    name: meshcentral
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIR_PORT
        value: 0
      - key: REDIR_ALIAS_PORT
        value: 0
      - key: BIND_HOST
        value: 0.0.0.0
      - key: MESHCENTRAL_CERT
        value: meshcentral-setup-main.onrender.com
